# Generated by Django 2.2.1 on 2019-05-23 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestpermis', '0002_auto_20190523_0552'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(default=50)),
                ('add_at', models.DateTimeField(auto_now=True)),
                ('candidat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='agent',
            name='user',
        ),
        migrations.AlterField(
            model_name='agent',
            name='candidat',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='permisconducteur',
            name='candidat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Candidat',
        ),
        migrations.AddField(
            model_name='permisconducteur',
            name='capital',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestpermis.CapitalPoint'),
            preserve_default=False,
        ),
    ]
