# Generated by Django 2.2.1 on 2019-05-27 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestpermis', '0006_auto_20190527_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='profil',
        ),
        migrations.RemoveField(
            model_name='profilcandidat',
            name='image',
        ),
    ]
