# Generated by Django 2.2.1 on 2019-05-27 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestpermis', '0008_candidat_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidat',
            old_name='User',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='prenom',
        ),
    ]
