# Generated by Django 2.2.1 on 2019-05-27 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestpermis', '0011_auto_20190527_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidat',
            old_name='data_burth',
            new_name='data',
        ),
    ]
