# Generated by Django 2.2.1 on 2019-05-27 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestpermis', '0013_auto_20190527_1443'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PermisConducteur',
            new_name='PermisConduir',
        ),
    ]
