# Generated by Django 2.2.1 on 2019-05-27 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestpermis', '0014_auto_20190527_1518'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PermisConduir',
            new_name='PermisConducteur',
        ),
    ]
