# Generated by Django 2.2.1 on 2019-05-27 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestpermis', '0015_auto_20190527_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='profil',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestpermis.ProfilCandidat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilcandidat',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
